// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: player.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Tech.Takenoko.Grpcspring.Proto {
  public static partial class Player
  {
    static readonly string __ServiceName = "tech.takenoko.grpcspring.proto.Player";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Tech.Takenoko.Grpcspring.Proto.MoveRequest> __Marshaller_tech_takenoko_grpcspring_proto_MoveRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tech.Takenoko.Grpcspring.Proto.MoveRequest.Parser));
    static readonly grpc::Marshaller<global::Tech.Takenoko.Grpcspring.Proto.MoveReply> __Marshaller_tech_takenoko_grpcspring_proto_MoveReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tech.Takenoko.Grpcspring.Proto.MoveReply.Parser));
    static readonly grpc::Marshaller<global::Tech.Takenoko.Grpcspring.Proto.ChangedRequest> __Marshaller_tech_takenoko_grpcspring_proto_ChangedRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tech.Takenoko.Grpcspring.Proto.ChangedRequest.Parser));
    static readonly grpc::Marshaller<global::Tech.Takenoko.Grpcspring.Proto.ChangedReply> __Marshaller_tech_takenoko_grpcspring_proto_ChangedReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tech.Takenoko.Grpcspring.Proto.ChangedReply.Parser));

    static readonly grpc::Method<global::Tech.Takenoko.Grpcspring.Proto.MoveRequest, global::Tech.Takenoko.Grpcspring.Proto.MoveReply> __Method_Move = new grpc::Method<global::Tech.Takenoko.Grpcspring.Proto.MoveRequest, global::Tech.Takenoko.Grpcspring.Proto.MoveReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Move",
        __Marshaller_tech_takenoko_grpcspring_proto_MoveRequest,
        __Marshaller_tech_takenoko_grpcspring_proto_MoveReply);

    static readonly grpc::Method<global::Tech.Takenoko.Grpcspring.Proto.ChangedRequest, global::Tech.Takenoko.Grpcspring.Proto.ChangedReply> __Method_Changed = new grpc::Method<global::Tech.Takenoko.Grpcspring.Proto.ChangedRequest, global::Tech.Takenoko.Grpcspring.Proto.ChangedReply>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "Changed",
        __Marshaller_tech_takenoko_grpcspring_proto_ChangedRequest,
        __Marshaller_tech_takenoko_grpcspring_proto_ChangedReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Tech.Takenoko.Grpcspring.Proto.PlayerReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Player</summary>
    [grpc::BindServiceMethod(typeof(Player), "BindService")]
    public abstract partial class PlayerBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Tech.Takenoko.Grpcspring.Proto.MoveReply> Move(global::Tech.Takenoko.Grpcspring.Proto.MoveRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task Changed(global::Tech.Takenoko.Grpcspring.Proto.ChangedRequest request, grpc::IServerStreamWriter<global::Tech.Takenoko.Grpcspring.Proto.ChangedReply> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Player</summary>
    public partial class PlayerClient : grpc::ClientBase<PlayerClient>
    {
      /// <summary>Creates a new client for Player</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public PlayerClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Player that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public PlayerClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected PlayerClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected PlayerClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Tech.Takenoko.Grpcspring.Proto.MoveReply Move(global::Tech.Takenoko.Grpcspring.Proto.MoveRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Move(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Tech.Takenoko.Grpcspring.Proto.MoveReply Move(global::Tech.Takenoko.Grpcspring.Proto.MoveRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Move, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Tech.Takenoko.Grpcspring.Proto.MoveReply> MoveAsync(global::Tech.Takenoko.Grpcspring.Proto.MoveRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return MoveAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Tech.Takenoko.Grpcspring.Proto.MoveReply> MoveAsync(global::Tech.Takenoko.Grpcspring.Proto.MoveRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Move, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::Tech.Takenoko.Grpcspring.Proto.ChangedReply> Changed(global::Tech.Takenoko.Grpcspring.Proto.ChangedRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Changed(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Tech.Takenoko.Grpcspring.Proto.ChangedReply> Changed(global::Tech.Takenoko.Grpcspring.Proto.ChangedRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_Changed, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override PlayerClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PlayerClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(PlayerBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Move, serviceImpl.Move)
          .AddMethod(__Method_Changed, serviceImpl.Changed).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, PlayerBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Move, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tech.Takenoko.Grpcspring.Proto.MoveRequest, global::Tech.Takenoko.Grpcspring.Proto.MoveReply>(serviceImpl.Move));
      serviceBinder.AddMethod(__Method_Changed, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Tech.Takenoko.Grpcspring.Proto.ChangedRequest, global::Tech.Takenoko.Grpcspring.Proto.ChangedReply>(serviceImpl.Changed));
    }

  }
}
#endregion
